### ISSUE TITLE
Regarding "Swagging-Post"

### ISSUE THREAD

**Issue by MyBooty165** [005Konz/Blooket-Cheats#3]
Hello Konz,

I am X-88, the owner of CybriaTech.

I'm here regarding the `swagging-post` user, I believe he "skidded" your code under CybriaTech's name.

I know swagging post personally and he said something along the lines of "He never skidded and found it on GitLab".

Personally, im not on anyone's side here as I have been inactive due to being grounded. But I would like to ask why you decided to target him out of every other skid out there.

I don't wanna get my group involved and I don't want CybriaTech's name being a skid group by 1 person who claims to be part of my group, I'm here to just clarify a few things and here to gain more insight on this matter.

If i dont respond, then im still grounded. i apologize for this incident and I will also try to prevent this and other incidents like these in the future.

**Comment by 005Konz** [comment]
Hello X-88,

Firstly to address swagging-post's claim to have "finding it on Gitlab," I would like to inform you that I am the one who created that Gitlab repository and I still update it in parallel with this one.

As to explain our distaste of swagging, it is due to past and current grudges. We believe that he previously "skidded" Jod's Blooket Cheats under the name SC0TT, and obviously you can see he's continuing this with mine. We have also had not so great experiences with him, as he tends to trash talk me and my work behind our backs which can be shown through screenshots by my server members and likely in message history you have access to. Lastly, he has claimed that we gave him permission to upload our work when clearly, we did not.

I personally apologize for any damage to CybriaTech's reputation, as I, nor do I think many in my server, are aware of swagging's connection to you.

I'll end this off by saying we hold nothing against you or CybriaTech, and dislike specifically swagging and his actions.

**Comment by MyBooty165** [comment]
Oh really? Thanks for the insight on this ordeal, nothing bad happened to my group and I’m trying to stop anything bad from happening before it gets worse.
It seemed like Scott never included the fact he was trying to make this problem worse, if what you’re saying is indeed true then I choose to not get involved in this further and you can do what you want with him. After all, this is YOUR code after all.

**Comment by 005Konz** [comment]
Thanks, though all I can really do is wait for his stolen content to inevitably break or people to realize he's been stealing from us.

**Comment by MyBooty165** [comment]
kk
